name: Generate QR Code and Display Image

on:
  push:
    branches:
      - main

jobs:
  set_up:
    runs-on : ubuntu-latest
  
    steps :
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install Dependencies
      run: go get -u github.com/skip2/go-qrcode
        
  generate_qrcode:
    needs: set_up
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate QR Code
      run: go run main.go

    - name: Save QR Code
      run: cp myqr.png $GITHUB_WORKSPACE/qr_generated.png

    - name: List files in $GITHUB_WORKSPACE
      run: ls $GITHUB_WORKSPACE